name: Terraform Azure DevSecOps CI/CD

on:
  push:
    branches:
      - main
      - "features/**"

  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  TF_VERSION: "1.9.8"
  TF_WORKING_DIR: "."

jobs:

  # ============================================================
  # 1. TERRAFORM VALIDATION
  # ============================================================

  terraform-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate


  # ============================================================
  # 2. TFLINT
  # ============================================================

  tflint:
    name: TFLint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: TFLint Version
        run: tflint --version

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --recursive


  # ============================================================
  # 3. TFSEC
  # ============================================================

  tfsec:
    name: tfsec Security Scan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          soft_fail: false


  # ============================================================
  # 4. TRUFFLEHOG
  # ============================================================

  trufflehog:
    name: TruffleHog Secret Scan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Full Git History
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog Scan
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified


  # ============================================================
  # 5. INFRACOST
  # ============================================================

  infracost:
    name: Infracost
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key:ico-xLYWa7sJ57LV5Ao49crw6ysYRVlZdRAX

      - name: Infracost Breakdown
        run: |
          infracost breakdown \
            --path . \
            --format table


  # ============================================================
  # 6. TERRAFORM PLAN
  # ============================================================

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    needs:
      - terraform-validate
      - tflint
      - tfsec
      - trufflehog
      - infracost

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      # --------------------------------------------------------
      # Azure OIDC Login
      # --------------------------------------------------------

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: c250a887-83bb-4856-96ee-b7916896f079
          tenant-id: 9fc55e6c-fd66-4dc3-8291-4392a2ad8c35
          subscription-id: 6e087706-38d2-46e4-b4f9-39ceebf097a2

      # --------------------------------------------------------
      # Terraform
      # --------------------------------------------------------

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
      working-directory: ./environment/prod
        run: terraform init

      - name: Terraform Plan
      working-directory: ./environment/prod
        run: terraform plan -out=tfplan

      # --------------------------------------------------------
      # Save Plan
      # --------------------------------------------------------

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan


  # ============================================================
  # 7. TERRAFORM APPLY
  # ONLY MAIN BRANCH
  # ============================================================

  terraform-apply:
    name: Terraform Apply
    working-directory: ./environment/prod
    runs-on: ubuntu-latest

    needs:
      - terraform-plan

    # Apply only after merge/push to main
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'

    environment:
      name: production

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      # --------------------------------------------------------
      # Azure OIDC Login
      # --------------------------------------------------------

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: c250a887-83bb-4856-96ee-b7916896f079
          tenant-id: 9fc55e6c-fd66-4dc3-8291-4392a2ad8c35
          subscription-id: 6e087706-38d2-46e4-b4f9-39ceebf097a2

      # --------------------------------------------------------
      # Terraform
      # --------------------------------------------------------

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init

      # --------------------------------------------------------
      # Download Plan
      # --------------------------------------------------------

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      # --------------------------------------------------------
      # APPLY
      # --------------------------------------------------------

      - name: Terraform Apply
      working-directory: ./environment/prod
        run: terraform apply -auto-approve tfplan
